# Generated by Django 5.2.10 on 2026-05-25 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_registrationsession_socialonboardingsession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationsession',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='registrationsession',
            name='last_name',
        ),
    ]
