# Generated by Django 5.2.10 on 2026-05-25 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_registrationsession_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationsession',
            name='first_name',
            field=models.CharField(default='Имя', max_length=150),
        ),
        migrations.AddField(
            model_name='registrationsession',
            name='last_name',
            field=models.CharField(default='Фамилия', max_length=150),
        ),
    ]
