# Generated by Django 5.2.10 on 2026-05-05 00:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AiDocumentDialog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('document_detection', 'Определение документа'), ('confirmation', 'Подтверждение'), ('document_selection', 'Выбор документа'), ('field_collection', 'Заполнение полей'), ('generation', 'Генерация')], default='document_detection', max_length=50)),
                ('template_name', models.CharField(blank=True, max_length=255, null=True)),
                ('values', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_document_dialog', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
