# Generated by Django 5.2.7 on 2025-11-10 20:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('1m', '1 месяц'), ('6m', '6 месяцев'), ('1y', '1 год')], max_length=2, verbose_name='тариф')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='начало подписки')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='окончание подписки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
        ),
    ]
