# Generated by Django 5.2.10 on 2026-05-10 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
        ('telegram_bot', '0003_telegramprofile_first_name_telegramprofile_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramprofile',
            name='current_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegram_profiles', to='chats.chatsession'),
        ),
    ]
