# Generated by Django 5.2.10 on 2026-05-11 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0004_telegramprofile_current_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramprofile',
            name='current_template_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
