# Generated by Django 5.2.10 on 2026-05-19 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0005_telegramprofile_current_template_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramprofile',
            name='pending_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='telegramprofile',
            name='registration_step',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
