# Generated by Django 5.2.10 on 2026-05-20 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0006_telegramprofile_pending_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramprofile',
            name='pending_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
